import fs from 'node:fs';
import path from 'node:path';
import prettier from 'prettier';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(scriptDir, '..');
const specPath = path.join(root, 'docs/openapi.json');
const outPath = path.join(root, 'packages/sdk/src/generated/client.ts');

const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'));

const requiredPaths = [
  '/flights/requests',
  '/flights/{flightId}/delay',
  '/flights/{flightId}',
  '/admin/capacity',
  '/admin/congestion'
];

for (const requiredPath of requiredPaths) {
  if (!spec.paths?.[requiredPath]) {
    throw new Error(`OpenAPI spec is missing required path: ${requiredPath}`);
  }
}

const content = `/* Auto-generated by scripts/generate-sdk.mjs from docs/openapi.json. Do not edit directly. */

export type FlightPriority = 'NORMAL' | 'INTERNATIONAL' | 'EMERGENCY';
export type FlightStatus = 'REQUESTED' | 'ASSIGNED' | 'HOLDING' | 'DELAYED' | 'FAILED' | 'CANCELLED';

export interface SubmitFlightRequest {
  airport_id: string;
  flight_id: string;
  airline_id: string;
  scheduled_arrival_time: string;
  aircraft_type: string;
  priority: FlightPriority;
  constraints?: {
    maxDelayMinutes?: number;
    preferredRunwayId?: string;
  };
}

export interface DelayUpdateRequest {
  airport_id: string;
  new_arrival_time: string;
  delay_reason: string;
}

export interface CapacityUpdateRequest {
  airport_id: string;
  runway_count: number;
  slot_minutes: number;
  lookahead_minutes: number;
  holding_lookahead_minutes: number;
  max_consecutive_per_airline: number;
  freeze_window_minutes: number;
}

export interface QueuedResponse {
  requestId: string;
  status: 'QUEUED';
}

export interface FlightStatusResponse {
  flight_id: string;
  airline_id: string;
  airport_id: string;
  status: FlightStatus;
  scheduled_arrival_time: string;
  priority: FlightPriority;
  last_updated_at: string;
}

export interface CapacityUpdateResponse {
  status: 'UPDATED';
  updated_at: string;
}

export interface CongestionMetricsResponse {
  airport_id: string;
  assigned_slots: number;
  runway_count: number;
  slot_minutes: number;
  congestion_index: number;
}

export interface ApiError {
  errorCode: string;
  message: string;
  correlationId: string;
  details?: Record<string, unknown>;
}

export interface SkyFlowClientConfig {
  baseUrl: string;
  getAccessToken?: () => string | Promise<string>;
  defaultHeaders?: Record<string, string>;
}

export class SkyFlowApiClient {
  constructor(private readonly config: SkyFlowClientConfig) {}

  private async request<T>(
    method: 'GET' | 'POST' | 'PUT',
    path: string,
    options?: {
      body?: unknown;
      headers?: Record<string, string>;
      query?: Record<string, string | number | undefined>;
    }
  ): Promise<T> {
    const url = new URL(path, this.config.baseUrl.endsWith('/') ? this.config.baseUrl : this.config.baseUrl + '/');
    if (options?.query) {
      for (const [key, value] of Object.entries(options.query)) {
        if (value !== undefined) {
          url.searchParams.set(key, String(value));
        }
      }
    }

    const authToken = this.config.getAccessToken ? await this.config.getAccessToken() : undefined;

    const response = await fetch(url.toString(), {
      method,
      headers: {
        'content-type': 'application/json',
        ...(authToken ? { authorization: 'Bearer ' + authToken } : {}),
        ...(this.config.defaultHeaders ?? {}),
        ...(options?.headers ?? {})
      },
      body: options?.body ? JSON.stringify(options.body) : null
    });

    if (!response.ok) {
      const errorBody = (await response.json().catch(() => undefined)) as ApiError | undefined;
      throw new Error(
        errorBody?.message ?? ('SkyFlow API request failed: ' + response.status + ' ' + response.statusText)
      );
    }

    return (await response.json()) as T;
  }

  submitFlightRequest(request: SubmitFlightRequest, idempotencyKey: string, correlationId?: string): Promise<QueuedResponse> {
    return this.request<QueuedResponse>('POST', '/flights/requests', {
      body: request,
      headers: {
        'Idempotency-Key': idempotencyKey,
        ...(correlationId ? { 'X-Correlation-Id': correlationId } : {})
      }
    });
  }

  submitDelayUpdate(flightId: string, request: DelayUpdateRequest): Promise<QueuedResponse> {
    return this.request<QueuedResponse>('POST', '/flights/' + encodeURIComponent(flightId) + '/delay', {
      body: request
    });
  }

  getFlightStatus(flightId: string, airportId: string): Promise<FlightStatusResponse> {
    return this.request<FlightStatusResponse>('GET', '/flights/' + encodeURIComponent(flightId), {
      query: { airport_id: airportId }
    });
  }

  updateCapacity(request: CapacityUpdateRequest): Promise<CapacityUpdateResponse> {
    return this.request<CapacityUpdateResponse>('PUT', '/admin/capacity', {
      body: request
    });
  }

  getCongestionMetrics(airportId: string): Promise<CongestionMetricsResponse> {
    return this.request<CongestionMetricsResponse>('GET', '/admin/congestion', {
      query: { airport_id: airportId }
    });
  }
}
`;

const prettierConfig = (await prettier.resolveConfig(outPath)) ?? {};
const formattedContent = await prettier.format(content, {
  ...prettierConfig,
  filepath: outPath
});

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, formattedContent, 'utf8');
console.log(`Generated SDK client from ${spec.info.title} v${spec.info.version} -> ${outPath}`);
